import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import router from './router';
import './styles.css';
import { useProgressStore } from './stores/progress';
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
app.use(router);
const progressStore = useProgressStore();
progressStore.init();
app.mount('#app');
